name: redis_client
version: 0.1.16
authors:
- Demis Bellot <demis.bellot@gmail.com>
- Adam Singer <financeCoding@gmail.com>
- Matias Meno <m@tias.me>
- Baruch Berger <baruchberger@gmail.com>
- Max Horstmann <max.horstmann@gmail.com>
- Matthew Butler <butler.matthew@gmail.com>
description: A high-performance async/non-blocking Redis client for Dart.
homepage: https://github.com/dartist/redis_client
environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  logging: ^1.0.2
dev_dependencies:
  test: ^1.21.1
  mockito: ^5.1.0
  benchmark_harness: 'any'
